TARGET := libz.a

include ../Makefile.common

all: $(TARGET)

$(TARGET):
	@cd zlib && ./configure
	@make -C zlib $(TARGET) CC="$(CC)" AR="$(AR)" RANLIB="$(RANLIB)" ARFLAGS="rcs"
	@cp zlib/$(TARGET) .
	@make -C zlib distclean

clean:
	@make -C zlib distclean
	@rm -f $(TARGET)
