TARGET := libz.a

MAKEFLAGS += --no-print-directory
QUIET := > /dev/null 2>&1

all: $(TARGET)

$(TARGET):
	@echo Building $(TARGET)...
	@cd zlib && ./configure $(QUIET)
	@$(MAKE) -C zlib $(TARGET) CC="$(CC)" AR="$(AR)" RANLIB="$(RANLIB)" ARFLAGS="rcs" $(QUIET)
	@cp zlib/$(TARGET) .
	@$(MAKE) -f $(lastword $(MAKEFILE_LIST)) zclean

zclean:
	@$(MAKE) -C zlib distclean $(QUIET)
	@rm -f zlib/*.wasm

clean: zclean
	@rm -f $(TARGET)
