TARGET := libmatoya.a

MAKEFLAGS += --no-print-directory
QUIET := > /dev/null 2>&1

all: $(TARGET)

$(TARGET):
	@echo Building $(TARGET)...
	@$(MAKE) -C matoya WASM=1 CC="$(CC)" AR="$(AR)" $(QUIET)
	@cp matoya/bin/web/wasm32/libmatoya.a .

clean:
	@$(MAKE) -C matoya clean $(QUIET)
	@rm -f libmatoya.a
