WASI_SDK := $(HOME)/wasi-sdk-16.0

WASI_SYSROOT := $(WASI_SDK)/share/wasi-sysroot
WASI_CC      := $(WASI_SDK)/bin/clang
WASI_CXX     := $(WASI_SDK)/bin/clang++

CC 	   := $(WASI_CC)  --sysroot=$(WASI_SYSROOT)
CXX	   := $(WASI_CXX) --sysroot=$(WASI_SYSROOT)
AR     := $(WASI_SDK)/bin/ar
RANLIB := $(WASI_SDK)/bin/ranlib

PLATFORM := emscripten
