WASI_SDK := $(HOME)/wasi-sdk-14.0
CC       := $(WASI_SDK)/bin/clang --sysroot=$(WASI_SDK)/share/wasi-sysroot
CXX	     := $(WASI_SDK)/bin/clang++ --sysroot=$(WASI_SDK)/share/wasi-sysroot
AR       := $(WASI_SDK)/bin/ar
RANLIB   := $(WASI_SDK)/bin/ranlib
