name: Docker Image CI

on:
  push:
    branches:
      - 'main'
      - 'emscripten'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: namaneo/junie:latest
      -
        name: Build and push
        if: github.ref == 'refs/heads/emscripten'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: namaneo/junie:emscripten
